/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.carapaceproxy.java-conventions")
    war
}

dependencies {
    providedCompile("javax:javaee-web-api:7.0")
}

description = "Carapace :: UI"

tasks.named<Jar>("jar") {
    isEnabled = true
}
