/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.carapaceproxy.java-conventions")
}

dependencies {
    implementation("io.projectreactor.netty:reactor-netty-core:1.0.23")
    implementation("io.projectreactor.netty:reactor-netty-http:1.0.23")
    implementation("io.netty:netty-tcnative-boringssl-static:2.0.54.Final")
    implementation("org.shredzone.acme4j:acme4j-client:2.12")
    implementation("org.shredzone.acme4j:acme4j-utils:2.12")
    implementation("org.bouncycastle:bcpkix-jdk15on:1.70")
    implementation("software.amazon.awssdk:route53:2.17.113")
    implementation("com.github.ben-manes.caffeine:caffeine:3.0.5")
    implementation("org.antlr:ST4:4.3.1")
    implementation("org.apache.zookeeper:zookeeper:3.7.0")
    implementation("org.apache.curator:curator-recipes:5.2.0")
    implementation("io.prometheus:simpleclient:0.14.1")
    implementation("io.prometheus:simpleclient_hotspot:0.14.1")
    implementation("io.prometheus:simpleclient_servlet:0.14.1")
    implementation("org.apache.bookkeeper.stats:prometheus-metrics-provider:4.14.4")
    implementation("io.micrometer:micrometer-registry-prometheus:1.8.2")
    implementation("org.herddb:herddb-jdbc:0.24.0")
    implementation("org.apache.commons:commons-lang3:3.12.0")
    implementation("org.apache.commons:commons-pool2:2.11.1")
    implementation("commons-io:commons-io:2.11.0")
    implementation("org.eclipse.jetty:jetty-server:9.4.44.v20210927")
    implementation("org.eclipse.jetty:jetty-webapp:9.4.44.v20210927")
    implementation("org.eclipse.jetty:jetty-servlet:9.4.44.v20210927")
    implementation("org.eclipse.jetty:jetty-util:9.4.44.v20210927")
    implementation("org.glassfish.jersey.core:jersey-server:2.35")
    implementation("org.glassfish.jersey.inject:jersey-hk2:2.35")
    implementation("org.glassfish.jersey.containers:jersey-container-servlet:2.35")
    implementation("org.glassfish.jersey.containers:jersey-container-jetty-http:2.35")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.13.1")
    implementation("com.fasterxml.jackson.core:jackson-core:2.13.1")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.13.1")
    implementation("javax.xml.bind:jaxb-api:2.3.1")
    implementation("org.glassfish.jaxb:jaxb-runtime:3.0.2")
    implementation("javax.activation:javax.activation-api:1.2.0")
    implementation("org.slf4j:slf4j-api:1.7.33")
    implementation("com.google.guava:guava:31.0.1-jre")
    implementation("org.projectlombok:lombok:1.18.22")
    runtimeOnly("org.glassfish.jersey.media:jersey-media-json-jackson:2.35")
    runtimeOnly("org.slf4j:slf4j-jdk14:1.7.33")
    runtimeOnly(project(":carapace-ui"))
    testImplementation("junit:junit:4.13.2")
    testImplementation("pl.pragmatists:JUnitParams:1.1.1")
    testImplementation("com.github.tomakehurst:wiremock-jre8:2.32.0")
    testImplementation("org.powermock:powermock-module-junit4:2.0.9")
    testImplementation("org.powermock:powermock-api-mockito2:2.0.9")
    testImplementation("org.mockito:mockito-core:3.12.4")
    testImplementation("org.apache.curator:curator-test:5.2.0")
    testImplementation("org.hamcrest:hamcrest:2.2")
    compileOnly("com.github.spotbugs:spotbugs-annotations:4.5.3")
}

description = "Carapace :: Server"
